name: Open & Close Issue
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          REQUEST_BODY: |
            {
              "body": "sleep 10s",
              "title": "Run Script"
            }
        id: create-issue
        uses: octokit/request-action@v2.x
        with:
          body: ${{ toJson(env.REQUEST_BODY) }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          route: POST /repos/{owner}/{repo}/issues
      - run: echo ${{ steps.create-issue.outputs.data }}
