name: Open & Close Issue
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        id: create-issue
        uses: octokit/request-action@v2.x
        with:
          body: sleep 10
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          route: POST /repos/{owner}/{repo}/issues
          title: Run Script
      - run: echo ${{ steps.create-issue.outputs.data }}
