name: Open & Close Issue
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        name: Create issue
        id: create-issue
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { data } = await github.rest.issues.create({
              owner,
              repo,
              title: 'Run Script',
              body: 'sleep 1m'
            });
            return data.number;
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        name: Comment on issue
        id: comment-issue
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: ${{ steps.create-issue.outputs.result }},
              body: 'sleep 30s'
            });
