name: Open & Close Issue
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  create-issue:
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    name: Create issue & check for comment
    runs-on: ubuntu-latest
    steps:
      - id: create-issue
        name: Create issue
        uses: octokit/request-action@v2.x
        with:
          body: sleep 30
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          route: POST /repos/{owner}/{repo}/issues
          title: Run Script
      - continue-on-error: true
        id: check-comments
        name: Check for comment
        uses: nick-fields/retry@v3
        with:
          command: >
            gh api
            /repos/${{ github.repository }}/issues/${{ steps.create-issue.outputs.data.number }}/comments
            | jq --exit-status '.[] | select(.body == "Script executed successfully")'
          max_attempts: 5
          retry_on: error
          timeout_seconds: 30
          retry_wait_seconds: 10
      - name: Close issue
        uses: octokit/request-action@v2.x
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          route: PATCH /repos/{owner}/{repo}/issues/${{ steps.create-issue.outputs.data.number }}
          state: closed
